### ISSUE TITLE
Response with delay missing?

### ISSUE THREAD

**Issue by fatmanmclone90** [alexvictoor/mock4net#11]
The two methods of implemnting described in the readme do not seem to be implemnted.  Neither the AfterDelay() or AddRequestProcessingDelay() are recgonised methods.

Am I missing something or are these not yet implemented?

thanks

**Comment by alexvictoor** [comment]
Hello
I guess this is my fault: I have mess up with semver versions, you might not be using latest version.  
Try version "1.0.0-beta1" which is the latest one: 

```
uninstall-package Mock4Net.Core
Install-Package Mock4Net.Core -Version 1.0.0-beta1 -Pre
```

Let me know if that solves your issue

**Comment by fatmanmclone90** [comment]
Great thanks, that version has the delay features.  Thanks for quick support
