### ISSUE TITLE
Generate package with SemVer on Nuget

### ISSUE THREAD

**Issue by tebeco** [alexvictoor/mock4net#22]
Currently trying to resolve the version returns this :

> paket find-package-versions nuget Mock4Net.Core
Paket version 3.29.1
1.0.0-v20150608-4f463ad
1.0.0-v20150608-3425eb4
1.0.0-beta1
1.0.0-alpha

### Expected 
> paket find-package-versions nuget Mock4Net.Core
Paket version 3.29.1
1.0.2
1.0.1
1.0.0-beta1
1.0.0-alpha

**Comment by pmiossec** [comment]
That's a really good idea but because that's an opensource project, I'm sure you should do a pull request to fix that!
