### ISSUE TITLE
TinyHttpServer should cancel HttpListener on Stop

### ISSUE THREAD

**Issue by ddizh** [alexvictoor/mock4net#26]
Currently when you call `server.Stop` it still listening to the port because HttpListener of TinyHttpServer never gets cancelled/stopped.

**Comment by StefH** [comment]
Hi @d-dizhevsky , if you are interested in the followup from this application, take a look at https://github.com/WireMock-Net/WireMock.Net which has a fix for this issue and has also more functionality available.

**Comment by ddizh** [comment]
@StefH I've already switched to WireMock, thanks. I think it would be better to archive this repo and adjust `README.md` so people can easily find it (WireMock).
